image: python:3.11

pages:
  stage: build
  script:
    - pip install --no-cache-dir -r dependencies.txt
    - pip install beautifulsoup4
    - python scripts/build_search_index.py
    - FLASK_APP=app.py flask freeze
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never # No runners will run on branches other than main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
