# iGEM Wiki Markdown转换配置文件

# 章节映射规则
section_mapping:
  "Description": 
    file: "description.html"
    title: "Project Description"
    lead: "Revolutionizing biological research with BIOMNIGEM - the first true multimodal AI biologist."
    
  "Engineering":
    file: "engineering.html" 
    title: "Engineering Success"
    lead: "Our Engineering Success: The Design → Build → Test → Learn Cycle for BIOMNIGEM."
    
  "Contribution":
    file: "contribution.html"
    title: "Contribution"
    lead: "Reshaping the Landscape of Synthetic Biology with BIOMNIGEM."
    
  "Notebook":
    file: "notebook.html"
    title: "Notebook"
    lead: "Our journey has been one of constant iteration and discovery - documenting every step from brainstorming to breakthrough."
    
  "Experiments":
    file: "experiments.html"
    title: "Experiments"
    lead: "Computational experiments designed to validate our hypotheses and demonstrate BIOMNIGEM's capabilities."
    
  "Hardware":
    file: "hardware.html"
    title: "Hardware"
    lead: "Computational Infrastructure: The High-Performance Computing Foundation Behind BIOMNIGEM."
    
  "Safety and Security":
    file: "safety-and-security.html"
    title: "Safety and Security"
    lead: "Building a powerful AI tool for biology comes with great responsibility - our comprehensive approach to safety and security."
    
  "Software":
    file: "software.html"
    title: "Software"
    lead: "BIOMNIGEM: Your Personal AI Biologist - Stop juggling dozens of separate tools. Start a conversation with your data."
    
  "Model":
    file: "model.html"
    title: "Model"
    lead: "The Architecture of BIOMNIGEM - A paradigm shift in biological AI through multimodal understanding."
    
  "Results":
    file: "results.html"
    title: "Results"
    lead: "Quantitative and Qualitative Performance - BIOMNIGEM demonstrates state-of-the-art performance across biological tasks."

# Markdown转换规则
conversion_rules:
  headers:
    h3: "^### (.*?)$"
    h4: "^#### (.*?)$"
    h5: "^##### (.*?)$"
  
  formatting:
    bold: "\\*\\*(.*?)\\*\\*"
    italic: "\\*(.*?)\\*"
    code: "`(.*?)`"
    
  lists:
    unordered: "^- (.*?)$"
    ordered: "^\\d+\\. (.*?)$"
  
  special:
    table_start: "^\\|"
    blockquote: "^> (.*?)$"

# HTML模板结构
templates:
  base: |
    {% extends "layout.html" %}
      
    {% block title %}{{TITLE}}{% endblock %}
    {% block lead %}{{LEAD}}{% endblock %}

    {% block page_content %}

    <div class="row mt-4">
      <div class="col">
        <div class="bd-callout bd-callout-info">
          <h4>{{MEDAL_CRITERION}}</h4>
          <p>{{MEDAL_DESCRIPTION}}</p>
          <hr />
          <p>Visit the <a href="https://competition.igem.org/judging/medals">Medals page</a> for more information.</p>
        </div>
      </div>
    </div>

    {{CONTENT}}

    {% endblock %}

# 奖章标准映射
medal_criteria:
  "Description":
    criterion: "Bronze Medal Criterion #1: Wiki"
    description: "Describe how and why you chose your iGEM project."
    
  "Engineering":
    criterion: "Silver Medal Criterion #1"
    description: "Demonstrate engineering success in a technical aspect of your project by going through at least one iteration of the engineering design cycle."
    
  "Contribution":
    criterion: "Bronze Medal Criterion #3"
    description: "Make a useful contribution for future iGEM teams and document it on this page."